const enc=new TextEncoder();
const SALT="CRHAI79+oGQqJLN6/z/Ftg==",HASH="ixjfzJqCp37oH+jNHZocniVofeVQIxLu4/MaQlfTo4Q=",ITER=850000,TTL=86400;
function j(d,s=200,h={}){return new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json; charset=utf-8",...h}})}
function b64(v){const r=atob(v);return Uint8Array.from(r,c=>c.charCodeAt(0))}
function eq(a,b){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a[i]^b[i];return d===0}
async function okpass(p){const k=await crypto.subtle.importKey("raw",enc.encode(p),"PBKDF2",false,["deriveBits"]);const x=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:b64(SALT),iterations:ITER},k,256);return eq(new Uint8Array(x),b64(HASH))}
function tok(){const a=new Uint8Array(32);crypto.getRandomValues(a);let s="";for(const b of a)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")}
function cookie(r,n){for(const p of (r.headers.get("cookie")||"").split(";")){const a=p.trim().split("=");if(a.shift()===n)return a.join("=")}return null}
async function auth(r,e){const t=cookie(r,"ns_admin_session");return t&&await e.INBOX.get("session:"+t)?t:null}
function c(v,m=5000){return String(v??"").trim().slice(0,m)}
function email(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)}
function page(){function t(){/*
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>North Star Ventures Admin</title>
<style>
:root{--n:#10263b;--g:#b79a60;--p:#f5f2e9;--m:#64717c;--l:rgba(16,38,59,.14);--r:#9e3d3d}*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,sans-serif;background:var(--p);color:#14202a}.w{width:min(1100px,calc(100% - 28px));margin:auto;padding:34px 0 60px}.brand{font:28px Georgia,serif;color:var(--n)}.small{font-size:12px;color:var(--m)}.card,.msg,.stat{background:#fff;border:1px solid var(--l);border-radius:12px}.card{padding:26px}.login{width:min(460px,100%);margin:12vh auto}.top,.row,.tools{display:flex;align-items:center;gap:10px}.top,.tools{justify-content:space-between}.top{margin-bottom:28px}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.stat{padding:18px}.stat b{display:block;font-size:28px;color:var(--n)}label{display:block;font-size:12px;font-weight:800;color:var(--n);margin:14px 0 8px;text-transform:uppercase;letter-spacing:.08em}input{width:100%;padding:13px;border:1px solid var(--l);border-radius:9px;font:inherit}button{border:0;border-radius:9px;padding:11px 15px;font-weight:800;cursor:pointer}.pri{background:var(--n);color:#fff}.sec{background:#eef1f3;color:var(--n)}.del{background:#f6e9e9;color:var(--r)}.tools{margin:20px 0}.tools input{max-width:360px}.msg{margin-bottom:12px;border-left:4px solid transparent;overflow:hidden}.msg.unread{border-left-color:var(--g)}.head{padding:16px;cursor:pointer;display:grid;grid-template-columns:1fr auto;gap:12px}.name{font-weight:900;color:var(--n)}.meta{font-size:12px;color:var(--m);margin-top:5px}.prev{font-size:14px;margin-top:8px}.body{display:none;padding:0 16px 16px;border-top:1px solid var(--l)}.msg.open .body{display:block}.body p{white-space:pre-wrap;line-height:1.65}.details{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin:16px 0}.d{padding:10px;background:#f7f8f8;border-radius:8px;font-size:13px}.d b{display:block;color:var(--n)}.badge{font-size:10px;font-weight:900;background:#f0ede5;padding:5px 8px;border-radius:999px}.empty{text-align:center;padding:50px;color:var(--m)}#err{color:var(--r);font-size:13px;margin-top:10px}@media(max-width:700px){.stats,.details{grid-template-columns:1fr}.top,.tools{align-items:stretch;flex-direction:column}.head{grid-template-columns:1fr}.tools input{max-width:none}}
</style></head><body><div class="w">
<section id="login" class="login card"><div class="brand">North Star Ventures</div><p class="small">Admin inbox</p><form id="lf"><label>Password</label><input id="pw" type="password" required><button class="pri" style="margin-top:14px">Sign in</button><div id="err"></div></form></section>
<section id="dash" hidden><div class="top"><div><div class="brand">North Star Ventures Admin</div><div class="small">Website inquiries and opportunity submissions</div></div><div class="row"><a href="/"><button class="sec" type="button">View site</button></a><button id="lo" class="sec">Log out</button></div></div>
<div class="stats"><div class="stat"><b id="u">0</b><span>Unread</span></div><div class="stat"><b id="tot">0</b><span>Total messages</span></div><div class="stat"><b id="wk">0</b><span>Last 7 days</span></div></div>
<div class="tools"><input id="q" placeholder="Search messages..."><button id="ref" class="sec">Refresh</button></div><div id="msgs"></div></section></div>
<script>
let A=[];function E(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
async function R(p,o){const r=await fetch(p,o||{});if(r.status===401)throw Error("AUTH");const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed");return d}
function F(d){try{return new Date(d).toLocaleString()}catch(e){return d}}function stats(){const n=Date.now();u.textContent=A.filter(x=>!x.read).length;tot.textContent=A.length;wk.textContent=A.filter(x=>n-new Date(x.createdAt).getTime()<604800000).length}
function render(){stats();const s=q.value.toLowerCase(),L=A.filter(m=>!s||[m.name,m.email,m.phone,m.company,m.type,m.message].join(" ").toLowerCase().includes(s));msgs.innerHTML=L.length?L.map(m=>'<article class="msg '+(!m.read?'unread':'')+'"><div class="head" onclick="this.parentElement.classList.toggle(\\'open\\')"><div><div class="name">'+E(m.name)+'</div><div class="meta">'+E(m.email)+' · '+F(m.createdAt)+'</div><div class="prev">'+E((m.message||"").slice(0,140))+'</div></div><span class="badge">'+E(m.type||"General")+'</span></div><div class="body"><div class="details"><div class="d"><b>Email</b>'+E(m.email)+'</div><div class="d"><b>Phone</b>'+E(m.phone||"—")+'</div><div class="d"><b>Company</b>'+E(m.company||"—")+'</div><div class="d"><b>Opportunity</b>'+E(m.type||"General")+'</div></div><p>'+E(m.message)+'</p><div class="row"><button class="sec" onclick="M(event,\\''+E(m.id)+'\\','+(!m.read)+')">'+(m.read?'Mark unread':'Mark read')+'</button><button class="del" onclick="D(event,\\''+E(m.id)+'\\')">Delete</button></div></div></article>').join(""):'<div class="empty card">No messages found.</div>'}
async function load(){try{const d=await R("/api/admin/messages");A=d.messages||[];login.hidden=true;dash.hidden=false;render()}catch(e){if(e.message==="AUTH"){login.hidden=false;dash.hidden=true}else alert(e.message)}}
window.M=async(e,id,r)=>{e.stopPropagation();await R("/api/admin/messages/"+encodeURIComponent(id)+"/read",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({read:r})});const m=A.find(x=>x.id===id);if(m)m.read=r;render()}
window.D=async(e,id)=>{e.stopPropagation();if(!confirm("Delete this message?"))return;await R("/api/admin/messages/"+encodeURIComponent(id),{method:"DELETE"});A=A.filter(x=>x.id!==id);render()}
lf.onsubmit=async e=>{e.preventDefault();err.textContent="";try{await R("/api/admin/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password:pw.value})});pw.value="";load()}catch(x){err.textContent=x.message==="AUTH"?"Incorrect password.":x.message}}
lo.onclick=async()=>{await fetch("/api/admin/logout",{method:"POST"});A=[];dash.hidden=true;login.hidden=false};ref.onclick=load;q.oninput=render;load()
</script></body></html>
*/}const s=t.toString();return new Response(s.slice(s.indexOf("/*")+2,s.lastIndexOf("*/")),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}})}
export default{async fetch(r,e){const u=new URL(r.url);
if(u.pathname==="/admin"||u.pathname==="/admin/")return page();
if(u.pathname==="/api/contact"&&r.method==="POST"){let b;try{b=await r.json()}catch{return j({error:"Invalid request."},400)}if(c(b.website,200))return j({ok:true});const name=c(b.name,120),em=c(b.email,180).toLowerCase(),phone=c(b.phone,80),company=c(b.company,160),type=c(b.type,120)||"General inquiry",message=c(b.message,6000);if(!name||!em||!message)return j({error:"Name, email, and message are required."},400);if(!email(em))return j({error:"Please enter a valid email address."},400);const ip=r.headers.get("cf-connecting-ip")||"unknown",h=Math.floor(Date.now()/3600000),rk="rate:"+ip+":"+h,n=Number(await e.INBOX.get(rk)||"0");if(n>=6)return j({error:"Too many submissions. Please try again later."},429);await e.INBOX.put(rk,String(n+1),{expirationTtl:3700});const id=String(Date.now()).padStart(13,"0")+"-"+crypto.randomUUID(),rec={id,createdAt:new Date().toISOString(),name,email:em,phone,company,type,message,read:false};await e.INBOX.put("msg:"+id,JSON.stringify(rec));return j({ok:true})}
if(u.pathname==="/api/admin/login"&&r.method==="POST"){let b;try{b=await r.json()}catch{return j({error:"Invalid request."},400)}if(!await okpass(String(b.password||"")))return j({error:"Incorrect password."},401);const t=tok();await e.INBOX.put("session:"+t,"1",{expirationTtl:TTL});return j({ok:true},200,{"set-cookie":"ns_admin_session="+t+"; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age="+TTL})}
if(u.pathname==="/api/admin/logout"&&r.method==="POST"){const t=cookie(r,"ns_admin_session");if(t)await e.INBOX.delete("session:"+t);return j({ok:true},200,{"set-cookie":"ns_admin_session=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0"})}
if(u.pathname==="/api/admin/messages"&&r.method==="GET"){if(!await auth(r,e))return j({error:"Unauthorized"},401);const l=await e.INBOX.list({prefix:"msg:",limit:200}),m=(await Promise.all(l.keys.map(async k=>{const x=await e.INBOX.get(k.name);try{return x?JSON.parse(x):null}catch{return null}}))).filter(Boolean).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));return j({messages:m})}
const rm=u.pathname.match(/^\/api\/admin\/messages\/([^/]+)\/read$/);if(rm&&r.method==="POST"){if(!await auth(r,e))return j({error:"Unauthorized"},401);const k="msg:"+decodeURIComponent(rm[1]),x=await e.INBOX.get(k);if(!x)return j({error:"Message not found."},404);const o=JSON.parse(x);let b={};try{b=await r.json()}catch{}o.read=!!b.read;await e.INBOX.put(k,JSON.stringify(o));return j({ok:true})}
const dm=u.pathname.match(/^\/api\/admin\/messages\/([^/]+)$/);if(dm&&r.method==="DELETE"){if(!await auth(r,e))return j({error:"Unauthorized"},401);await e.INBOX.delete("msg:"+decodeURIComponent(dm[1]));return j({ok:true})}
return e.ASSETS.fetch(r)}};